---
- name: configure a mail server
  hosts: do
  remote_user: root
  gather_facts: False # disabled for testing only
  vars_files:
    - ./variables.yml

  tasks:
    #- name: Check if host is Debian
    #  fail: msg="Only Debian is supported at the moment"
    #  when: ansible_facts['distribution'] != "Debian"
      #    - name: Run the equivalent of "apt-get update" as a separate step
      #      apt:
      #        update_cache: yes
      #    - name: Run the equivalent of "apt-get full-upgrade" as a separate step
      #      apt:
      #        upgrade: full
    - name: Install dependencies
      apt:
        pkg: '{{ dependencies }}'
    - name: Disable unwanted firewall-related services
      systemd:
        name: '{{ item }}'
        state: stopped
        enabled: no
        masked: yes
      loop: '{{ obsolete_fw }}'
    - name: Enable firewalld
      systemd:
        name: firewalld
        state: started
    - name: Set drop as default zone
      command: firewall-cmd --set-default-zone=public

