---
- name: configure a mail server
  hosts: do
  remote_user: root
  gather_facts: true # disable for fast testing only
  vars:
    fqdn: headbeef.xyz
  vars_files:
    - ./variables.yml

  tasks:
    # - name: Check if host is Debian
    #   fail: msg="Only Debian is supported at the moment"
    #   when: ansible_facts['distribution'] != "Debian"
    # - name: Run the equivalent of "apt-get update" as a separate step
    #   apt:
    #   update_cache: yes
    # - name: Run the equivalent of "apt-get full-upgrade" as a separate step
    #   apt:
    #   upgrade: full
    - name: Install dependencies
      apt:
        pkg: '{{ dependencies }}'
    - name: Disable unwanted firewall-related services
      systemd:
        name: '{{ item }}'
        state: stopped
        enabled: false
        masked: true
      loop: '{{ obsolete_fw }}'
    - name: Enable firewalld
      systemd:
        name: firewalld
        state: started
        enabled: true
        masked: false
    - block:
      - name: Set drop as default firewall zone
        command: "firewall-cmd --set-default-zone=drop"
      - name: Reload firewalld to apply changes
        command: "firewall-cmd --reload"
    - name: Enable ssh access on default zone
      firewalld:
        service: ssh
        permanent: true
        state: enabled
        immediate: true
    - name: permit traffic in default zone for needed services
      firewalld:
        port: '{{ item }}'
        permanent: true
        state: enabled
        immediate: true
      loop: '{{ open_ports }}'
    - name: Set hostname
      hostname:
        name: '{{ fqdn }}'
        use: systemd
    - name: Change /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1'
        line: 127.0.1.1 {{ fqdn }}
